### ISSUE TITLE
Rozejrzeć się przed podjęciem czynności

### ISSUE THREAD

**Issue by kubasikora** [PW-EITI-STERO-18Z/velma_STERO-18Z-Winnicki-Sikora#4]

**Comment by stratixx** [comment]
rozglądanie się zawiera wykrycie stolika z puszką(źródło) i stolika bez puszki(cel)

**Comment by kubasikora** [comment]
symulator dostarcza nam tfy obiektów, nóg od stołów i puszki, 
rozejrzenie się ma na celu tylko wykrycie innych przeszkód oraz odblokowanie planera
